name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: test.tex
      - name: Make copies
        run: |
          mkdir -p out
          cp ./test.pdf ./test-${GITHUB_REF#refs/heads/}.pdf
          cp ./test.pdf ./test-${GITHUB_REF#refs/heads/}-$(date +'%Y-%m-%d')-${{ github.sha }}.pdf
      - name: Setup and add
        run: |
          git config --global user.name "Latex_build_bot"
          git config --global user.email "david.sprunger@gmail.com"
          git checkout build
          git add ./test-${GITHUB_REF#refs/heads/}.pdf
          git add ./test-${GITHUB_REF#refs/heads/}-$(date +'%Y-%m-%d')-${{ github.sha }}.pdf
          git commit -m "new builds"
          git push origin
