name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: test.tex
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Make main copy
        run: mkdir -p out && mv test.pdf ./out/test-${{ steps.extract_branch.outputs.branch }}.pdf
      - name: Make reserve copy
        run: cp ./out/test.pdf ./out/test-${{ steps.extract_branch.outputs.branch }}-$(date +'%Y-%m-%d')-${{ github.sha }}.pdf
      - name: Release
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: build
          force_orphan: true

