name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: test.tex
      - name: Make copies
        run: |
          cp ./test.pdf ./test-${GITHUB_REF#refs/heads/}.pdf
          cp ./test.pdf ./test-${GITHUB_REF#refs/heads/}-$(date +'%Y-%m-%d')-${{ github.sha }}.pdf
          git config --global user.name "Latex build bot"
          git config --global user.email "<>"
          git add ./test-*.pdf
          git commit -m "new builds"
          git push origin
